### ISSUE TITLE
Same ingress or service name in multiple Kubernetes namespaces

### ISSUE THREAD

**Issue by dpbevin** [microsoft/reverse-proxy#1389]
When defining Ingress or Service resources in Kubernetes, it is legal to have two ingresses with the same name but in different *namespaces*. It is the combination of name and namespace that make the resource unique.

Yarp currently does *not* include the namespace when creating the keys for the Cluster and Routes configuration.

(Example ingresses shown here with the spec section omitted for clarity)
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-ingress
  namespace: ns-one
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-ingress
  namespace: ns-two
```
