### ISSUE TITLE
Kubernetes Ingress Class Support

### ISSUE THREAD

**Issue by dpbevin** [microsoft/reverse-proxy#1397]
### Background

[Kubernetes 1.18 introduced](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/) a standard mechanism for assigning individual Ingress resources to specific Ingress Controllers, using the `ingressClassName` field on Ingresses and the *IngressClass* resource. Up to that point, Ingress Controllers used a custom annotation `kubernetes.io/ingress.class` on Ingress resources but in subtly different ways.

Kubernetes 1.22 (released Oct 2021) removed the beta Ingress resource API which means that all Ingress resources support the `ingressClassName` field.

### Why is this important?

Support for `IngressClass` means that groups of Ingress resources can be explicitly allocated to specific instances of an Ingress Controller, thereby segregating your traffic.

For example, you may run two Ingress Controllers in a cluster: one for external access, the other for internal access. You could set the `ingressClassName` field for your public APIs to `yarp-public` , and your monitoring Ingresses to `yarp-internal`.

Another example would be to run multiple Ingress Controller deployments/daemonsets to help distribute the load more effectively.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-ingress
  namespace: default
spec:
  ingressClassName: yarp
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: the-service
                port: 
                  name: http
```
