### ISSUE TITLE
Kubernetes Ingress Controller configures Route metadata

### ISSUE THREAD

**Issue by specialforest** [microsoft/reverse-proxy#1479]
### What should we add or change to make your life better?
We need a way to specify metadata in Ingress object and make Kubernetes Ingress Controller populate Metadata field of RouteConfig.

### Why is this important to you?
I'd like to use Route Metadata to configure custom middlewares in Reverse Proxy.

**Comment by specialforest** [comment]
To specify metadata we could use annotations. Define a prefix, e.g. "metadata.yarp.ingress.kubernetes.io":
```yaml
annotations:
  metadata.yarp.ingress.kubernetes.io/foo: bar
  metadata.yarp.ingress.kubernetes.io/another-key: value
```
A single Ingress object can define multiple paths and they are converted into multiple routes in Reverse Proxy. Here I propose to copy metadata to each of these routes.
