### ISSUE TITLE
Ingress Controller and grpc

### ISSUE THREAD

**Issue by code101-amagi** [microsoft/reverse-proxy#1835]
Hi,

For grpc to work without ssl i need follow https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/grpc.md

In case of ingress controller i can change Kestrel options in ingress-controller.yaml file  "samples\KubernetesIngress.Sample\Combined" by changing deployment part and adding env variables like

``` 
env:
            - name: Kestrel__Endpoints__http__Url
              value: http://*:8000
            - name: Kestrel__Endpoints__http__Protocols
              value: Http2
```
but how do i change the required cluster version like in sample

```json
"cluster1": {
  "HttpRequest": {
    "Version": "2",
    "VersionPolicy": "RequestVersionExact"
  },
```
Is there a way to do this? using Annotations or something else?

Thanks
