### ISSUE TITLE
Ingress controller and grpc

### ISSUE THREAD

**Issue by dp-code101** [microsoft/reverse-proxy#1836]
Hi,

For grpc to work without ssl i need follow https://github.com/microsoft/reverse-proxy/blob/main/docs/docfx/articles/grpc.md

In case of ingress controller i can change Kestrel options in ingress-controller.yaml file  "samples\KubernetesIngress.Sample\Combined" by changing deployment part and adding env variables like

``` yaml
env:
 - name: Kestrel__Endpoints__http__Url
    value: http://*:8000
 - name: Kestrel__Endpoints__http__Protocols
    value: Http2
```
but how do i change the required cluster version like in sample

```json
"cluster1": {
  "HttpRequest": {
    "Version": "2",
    "VersionPolicy": "RequestVersionExact"
  },
```
Is there a way to do this? using Annotations or something else?

Thanks

**Comment by MihaZupan** [comment]
As long as the destination server supports HTTP/2, you don't have to explicitly set anything as H2 will be used by default.

All currently-supported annotations are documented [here](https://github.com/microsoft/reverse-proxy/tree/main/samples/KubernetesIngress.Sample#annotations).
There's currently no way to set `HttpRequest` options through annotations, though I don't see why we couldn't add it.

You can customize this through code by modifying the `Combined` project and registering a [config filter](https://microsoft.github.io/reverse-proxy/articles/config-filters.html) like
```c#
public sealed class CustomConfigFilter : IProxyConfigFilter
{
    public ValueTask<ClusterConfig> ConfigureClusterAsync(ClusterConfig cluster, CancellationToken cancel)
    {
        if (cluster.ClusterId.Contains("grpc"))
        {
            cluster = cluster with
            {
                HttpRequest = cluster.HttpRequest with
                {
                    Version = HttpVersion.Version20,
                    VersionPolicy = HttpVersionPolicy.RequestVersionExact
                }
            };
        }

        return new ValueTask<ClusterConfig>(cluster);
    }

    public ValueTask<RouteConfig> ConfigureRouteAsync(RouteConfig route, ClusterConfig cluster, CancellationToken cancel) => new(route);
}
```

**Comment by dp-code101** [comment]
Thanks, i have already added annotation for HttpRequest just to test if it's working when setting version, and it works 

something like this

```yaml
 annotations:
    yarp.ingress.kubernetes.io/load-balancing: "LeastRequests"
    yarp.ingress.kubernetes.io/cluster-request: |
      Version: "2"
      VersionPolicy: "RequestVersionExact"
```
did't know about proxy config filter, will try to use that.

for cluster id, from what i can see it's key that is composed at runtime, 

```csharp
$"{ingressServiceBackend.Name}.{namespaceName}:{ingressServiceBackend.Port.Number}"
---
$"{ingressServiceBackend.Name}.{namespaceName}:{ingressServiceBackend.Port.Name}"
```
so in case that i have ingress yaml like this

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-service-ingress
  annotations:
    yarp.ingress.kubernetes.io/load-balancing: "LeastRequests"
spec:
  ingressClassName: yarp
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weather-service
            port:
              number: 9002
```

for CustomConfigFilter to work i need to change to something like

```yaml
 spec:
  ingressClassName: yarp
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weather-service-grpc
            port:
              number: 9002
```
can't use port name in this case? 
like

```yaml
  service:
            name: weather-service
            port:
              number: 9002
              name: grpc
```

PS: Yarp.Kubernetes.Controller library is not available on nuget?

Thanks
