### ISSUE TITLE
update ingress status after loaded

### ISSUE THREAD

**Issue by witskeeper** [microsoft/reverse-proxy#1910]
### What should we add or change to make your life better?
when the ingress loaded by  ingress controller ,  can update the ingress `status` so we can display the ingress  ip info.
like what the `updateRegularIngressStatusAndEvent` do in `NGINX Ingress Controller`.
see  [How NGINX Ingress Controller Works](https://docs.nginx.com/nginx-ingress-controller/intro/how-nginx-ingress-controller-works/)
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
spec:
  ingressClassName: ingress-yarp
  rules:
    - host: abc.com
      http:
        paths:
          - backend:
              service:
                name: abc
                port:
                  number: 8081
            path: /
            pathType: Prefix
status:
  loadBalancer:
    ingress:
      - ip: 172.10.10.40
```

### Why is this important to you?
this is good for the manager  who  check the list of ingresses.
