### ISSUE TITLE
Support for addition of Multiple Host Domains in K8s Ingress Rules

### ISSUE THREAD

**Issue by unknownstring** [microsoft/reverse-proxy#1950]
### Yarp.Kubernetes.Controller
We currently use Nginx as Ingress controller for our endpoints in K8s. However, there are a few shortcomings and as our technology stack is .NET based, we consider using Yarp instead. 

Our Nginx rules are 'project' based, hence we use subdomains to organize and target individual related services.

Ingress manifest with multiple host domains for one external IP:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repro-1-ingress
  namespace: foo
spec:
  ingressClassName: yarp-ingress
  rules:
    - host: 'subdomain1.example.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: repro-1-service
                port:
                  name: http
    - host: 'subdomain2.example.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: repro-2-service
                port:
                  name: http
```

Current workaround, split into two ingress manifests:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repro-1-ingress-for-subdomain1
  namespace: foo
spec:
  ingressClassName: yarp-ingress
  rules:
    - host: 'subdomain1.example.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: repro-1-service
                port:
                  name: http
```
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: repro-1-ingress-for-subdomain2
  namespace: foo
spec:
  ingressClassName: yarp-ingress
  rules:
    - host: 'subdomain2.example.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: repro-2-service
                port:
                  name: http
```

### Include host domain as part of the route naming
Due to Ingress manifest parsing and Yarp route id naming, this is not currently possible. 

Hence, suggestion is to include host domain as part of the route naming. This reduces duplicating Ingress manifests and additionally bundles related host domains in Azure Ingress overview.
