### ISSUE TITLE
Kubernetes External Service support

### ISSUE THREAD

**Issue by nquandt** [microsoft/reverse-proxy#2017]
### What should we add or change to make your life better?

Kubernetes External Service support.

### Why is this important to you?

Allow DNS resolution to external services "behind" proxy.

---

External Service [(kubernetes docs)](https://kubernetes.io/docs/concepts/services-networking/service/#externalname)
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  type: ExternalName
  externalName: my.database.example.com # This would be the hostname resolution
```

Ingress
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: default
spec:
  ingressClassName: yarp
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-service
            port:
              number: 443 # NOTE This is how we would pull protocol.. since ExternalName services don't have a port prop.
```

Plug into the [HandleIngressRule](https://github.com/microsoft/reverse-proxy/blob/029e731a95c08a77af37700b1ab6ecd99e694d83/src/Kubernetes.Controller/Converters/YarpParser.cs#L48) method of `Converters/YarpParser.cs`

Naive approach

```csharp
private static void HandleIngressRule(YarpIngressContext ingressContext, List<Endpoints> endpoints, 
    IList<V1EndpointSubset> defaultSubsets, V1IngressRule rule, YarpConfigContext configContext)
{
  var http = rule.Http;
  foreach (var path in http.Paths ?? Enumerable.Empty<V1HTTPIngressPath>())
  {
    var service = ingressContext.Services.SingleOrDefault(s => s.Metadata.Name == path.Backend.Service.Name);
    if (service.Spec != null)
    {
      // We already have access to the service specs... so just handle it if its an ExternalName
      if (service.Spec.Type == "ExternalName")
      {
        // Just add a method for adding the RouteConfigs? or provide an override for the other IngressRulePath?
        HandleIngressRuleForExternalName(ingressContext, path.Backend.Service.Port, service.Spec.ExternalName, rule, path, configContext);
      }
      else
      {
        var servicePort = service.Spec.Ports.SingleOrDefault(p => MatchesPort(p, path.Backend.Service.Port));
        if (servicePort != null)
        {
          HandleIngressRulePath(ingressContext, servicePort, endpoints, defaultSubsets, rule, path, configContext);
        }
      }
    }
  }
}
```

I am willing to submit a PR for this, given a little direction on if it would be better to create a new method, or add an override to HandleIngressRulePath? Or add a a new private method?

Something like this? The only issue I see is ALOT of duplicated logic for creating the Routeconfig... which wouldn't really want to have to manage it twice for every update.
```csharp
private static void HandleIngressRuleForExternalName(YarpIngressContext ingressContext, V1ServiceBackendPort servicePort, 
    string externalName, V1IngressRule rule, V1HTTPIngressPath path, YarpConfigContext configContext)
{
    var backend = path.Backend;
    var ingressServiceBackend = backend.Service;

    var clusters = configContext.ClusterTransfers;
    var routes = configContext.Routes;

    // Each ingress rule path can only be for one service
    var key = UpstreamName(ingressContext.Ingress.Metadata.NamespaceProperty, ingressServiceBackend);
    if (!clusters.ContainsKey(key))
    {
        clusters.Add(key, new ClusterTransfer());
    }

    var cluster = clusters[key];
    cluster.ClusterId = key;
    cluster.LoadBalancingPolicy = ingressContext.Options.LoadBalancingPolicy;
    cluster.SessionAffinity = ingressContext.Options.SessionAffinity;
    cluster.HealthCheck = ingressContext.Options.HealthCheck;
    cluster.HttpClientConfig = ingressContext.Options.HttpClientConfig;

    var pathMatch = FixupPathMatch(path);
    var host = rule.Host;

    routes.Add(new RouteConfig()

    {
        Match = new RouteMatch()
        {
            Hosts = host is not null ? new[] { host } : Array.Empty<string>(),
            Path = pathMatch
        },
        ClusterId = cluster.ClusterId,
        RouteId = $"{ingressContext.Ingress.Metadata.Name}.{ingressContext.Ingress.Metadata.NamespaceProperty}:{host}{path.Path}",
        Transforms = ingressContext.Options.Transforms,
        AuthorizationPolicy = ingressContext.Options.AuthorizationPolicy,
#if NET7_0_OR_GREATER
        RateLimiterPolicy = ingressContext.Options.RateLimiterPolicy,
#endif
        CorsPolicy = ingressContext.Options.CorsPolicy,
        Metadata = ingressContext.Options.RouteMetadata,
        Order = ingressContext.Options.RouteOrder,
    });

    var protocol = servicePort.Number == 443 ? "https" : "http";
    var uri = $"{protocol}://{externalName}:{servicePort.Number}";
    cluster.Destinations[uri] = new DestinationConfig()
    {
        Address = uri
    };
}
```
