### ISSUE TITLE
Direct Forwarding doesn't work inside docker compose

### ISSUE THREAD

**Issue by alexandrereyes** [microsoft/reverse-proxy#2040]
I have two projects inside a docker compose, the second one has YARP 2.0 with direct forwarding configured. When the first one make an http request to the second, it should enter on `"/{**catch-all}"` map, but it doesn't. 
This problem only occurs inside docker compose, if I set the project-2 as startup project and run within docker only, it works properly.

Project-1 ` Program.cs`
```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHttpClient();

var app = builder.Build();

app.MapGet("/", () => "Project 1!");

app.MapGet("/get-project-2", async (IHttpClientFactory httpClientFactory) =>
{
    var httpClient = httpClientFactory.CreateClient();
    return await httpClient.GetStringAsync("http://project-2");
});

app.Run();

```

Project-2 `Program.cs`
```
using System.Diagnostics;
using System.Net;
using Yarp.ReverseProxy.Forwarder;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddHttpForwarder();

var app = builder.Build();

app.UseRouting()
    .UseEndpoints(endpoints =>
    {
        endpoints.Map("{**catch-all}", async httpContext =>
        {
            // when running inside docker compose, this code is never hitted but works when I set the project-2 as startup project
            await app.Services.GetRequiredService<IHttpForwarder>().SendAsync(
                httpContext,
                httpContext.Request.Host.ToString(),
                new HttpMessageInvoker(new SocketsHttpHandler()
                {
                    UseProxy = false,
                    AllowAutoRedirect = false,
                    AutomaticDecompression = DecompressionMethods.All,
                    UseCookies = false,
                    ActivityHeadersPropagator = new ReverseProxyPropagator(DistributedContextPropagator.Current)
                })
            );
        });
    });

app.MapGet("/", () => "Project 2!");

app.Run();

```

Docker compose file:
```
version: '3.4'

services:
  project-1:
    image: ${DOCKER_REGISTRY-}project1
    build:
      context: .
      dockerfile: Project-1/Dockerfile

  project-2:
    image: ${DOCKER_REGISTRY-}project2
    build:
      context: .
      dockerfile: Project-2/Dockerfile

```

Here is a repo which reproduces the issue:
https://github.com/alexandrereyes/alexandrereyes-yarp-directforwarding-problem

Any help?
