### ISSUE TITLE
How to config yarp.json to add or remove part of route? 

### ISSUE THREAD

**Issue by YoChen** [microsoft/reverse-proxy#2109]
eg:

from http://abc.com/a/b/{everything}
to http://cba.com/b/{everything}

or 

from http://abc.com/a/b/{everything}
to http://cba.com/c/{everything}

or

from http://abc.com/a/b/{everything}
to http://abc.com/c/a/b/{everything}

can you help me ,if  yarp.json can archive. very thanks.

**Comment by pinkfloydx33** [comment]
Generally speaking, you _could_ use two [transforms](https://microsoft.github.io/reverse-proxy/articles/transforms.html#request-transforms): one to strip/remove the existing path prefix and a second transform to add a new prefix. That said, only your second case would require both; the first example only needs prefix removal while the third only needs to add a prefix. 

<details>
  <summary>Example Configuration</summary>

```yaml
// *snip*
"ReverseProxy": {
   "routes": {
      "route1": {
         "ClusterId": "cluster1",
         "Match": {
            "Path": "/a/b/{**catchall}"
         },
         "Transforms": [
            {
               "PathRemovePrefix": "/a"
            }
         ]
      },
      "route2": {
         "ClusterId": "cluster1",
         "Match": {
            "Path": "/a/b/{**catchall}"
         },
         "Transforms": [
            {
               "PathRemovePrefix": "/a/b"
            },
            {
               "PathPrefix": "/c"
            }
         ]
      },
      "route3": {
         "ClusterId": "cluster2",
         "Match": {
            "Path": "/a/b/{**catchall}"
         },
         "Transforms": [
            {
               "PathPrefix": "/c"
            }
         ]
      }
   },
   "Clusters": {
      "cluster1": {
         "Destinations": {
            "clustser1/backend": {
               "Address": "http://www.cba.com/"
            }
         }
      },
      "cluster2": {
         "Destinations": {
            "clustser2/backend": {
               "Address": "http://www.abc.com/"
            }
         }
      }
   }   
}
```

</details>
