### ISSUE TITLE
Kubernetes Controller Support External names

### ISSUE THREAD

**Issue by HappyCodeSloth** [microsoft/reverse-proxy#2230]
### What should we add or change to make your life better?

The Kubernetes Controller supports routing currently to Services within the cluster. By using Endpoint Slices this can be made to work with Services hosted externally to the cluster if there is a list of known Ip's. However, in my case I have a DNS Name that say points to a CDN for example Azure Front Door. As such, Support for [External Name](https://github.com/HappyCodeSloth/reverse-proxy.git) type services would be best. 

#### Example

``` yaml 
apiVersion: v1
kind: Service
metadata:
  name: my-external-service
spec:
  type: ExternalName
  externalName: my.external-service.example.com
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    yarp.ingress.kubernetes.io/backend-protocol: https
spec:
  ingressClassName: my-yarp-controller-ingress-class
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: my-external-service
            port:
              number: 443
```

### Why is this important to you?

Enables the Yarp Kubernetes Controller to be used to proxy to services hosted externally from the cluster without knowledge of underlying IPs using native Kubernetes Configuration.
